import Head from "next/head";
import Layout from "../components/Layout";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Next Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout title="Home">
          <p>Welcome to the home page!</p>
        </Layout>
      </main>
    </div>
  );
};

export default Home;
